"""
Конфигурация приложения.
"""

from core.config.base import BaseSettings, get_settings, set_settings, settings
from core.config.loader import load_merged_config
from core.config.models import (
    AuthConfig,
    AuthProviderConfig,
    BothubProviderConfig,
    CallsConfig,
    CloudRuSTTConfig,
    CloudRuTTSBackendConfig,
    DatabaseConfig,
    DemoAuthConfig,
    LitserveSpeechBackendConfig,
    LLMConfig,
    LocalSileroVADBackendConfig,
    LoggingConfig,
    ModelConfig,
    OpenAIProviderConfig,
    OpenRouterFreePoolConfig,
    OpenRouterProviderConfig,
    ProxyConfig,
    S3BucketConfig,
    S3Config,
    SberSTTBackendConfig,
    SberTTSBackendConfig,
    ServerConfig,
    SpeechProvidersConfig,
    STTProvidersConfig,
    TTSProvidersConfig,
    VADProvidersConfig,
    YandexLLMProviderConfig,
    YandexSTTBackendConfig,
    YandexTTSBackendConfig,
)
from core.config.testing import is_testing

__all__ = [
    "BaseSettings",
    "get_settings",
    "set_settings",
    "settings",
    "load_merged_config",
    "is_testing",
    "AuthConfig",
    "AuthProviderConfig",
    "DemoAuthConfig",
    "CallsConfig",
    "DatabaseConfig",
    "LoggingConfig",
    "ServerConfig",
    "ProxyConfig",
    "OpenAIProviderConfig",
    "OpenRouterFreePoolConfig",
    "OpenRouterProviderConfig",
    "BothubProviderConfig",
    "YandexLLMProviderConfig",
    "ModelConfig",
    "LLMConfig",
    "S3BucketConfig",
    "S3Config",
    "SpeechProvidersConfig",
    "STTProvidersConfig",
    "TTSProvidersConfig",
    "VADProvidersConfig",
    "LitserveSpeechBackendConfig",
    "CloudRuSTTConfig",
    "CloudRuTTSBackendConfig",
    "YandexSTTBackendConfig",
    "YandexTTSBackendConfig",
    "SberSTTBackendConfig",
    "SberTTSBackendConfig",
    "LocalSileroVADBackendConfig",
]
