"""LLM client package import path for model routing helpers."""

from __future__ import annotations

from core.llm_model_routing import (
    ACCOUNT_FREE_TIER_LLM_PROVIDER_SLUGS,
    HUMANITEC_LLM_AUTO_MODEL,
    HUMANITEC_LLM_PROVIDER,
    HUMANITEC_LLMS_DISPLAY_LABEL,
    LLM_FREE_MODEL_DISCOVERY_POLICY_BY_PROVIDER,
    LLM_ROUTING_PROVIDER_SLUGS,
    OPENAI_COMPATIBLE_LLM_PROVIDER_ORDER,
    OPENAI_COMPATIBLE_LLM_PROVIDER_SLUGS,
    PLATFORM_FREE_MODEL_CANDIDATE_PROVIDER_SLUGS,
    PLATFORM_LLM_PROVIDER_ORDER,
    PLATFORM_LLM_PROVIDER_SLUGS,
    ZERO_PRICE_LLM_PROVIDER_SLUGS,
    humanitec_llms_model_ref,
    split_humanitec_llms_model_ref,
    split_provider_prefixed_model,
)

__all__ = [
    "ACCOUNT_FREE_TIER_LLM_PROVIDER_SLUGS",
    "HUMANITEC_LLM_AUTO_MODEL",
    "HUMANITEC_LLM_PROVIDER",
    "HUMANITEC_LLMS_DISPLAY_LABEL",
    "LLM_FREE_MODEL_DISCOVERY_POLICY_BY_PROVIDER",
    "LLM_ROUTING_PROVIDER_SLUGS",
    "OPENAI_COMPATIBLE_LLM_PROVIDER_ORDER",
    "OPENAI_COMPATIBLE_LLM_PROVIDER_SLUGS",
    "PLATFORM_FREE_MODEL_CANDIDATE_PROVIDER_SLUGS",
    "PLATFORM_LLM_PROVIDER_ORDER",
    "PLATFORM_LLM_PROVIDER_SLUGS",
    "ZERO_PRICE_LLM_PROVIDER_SLUGS",
    "humanitec_llms_model_ref",
    "split_humanitec_llms_model_ref",
    "split_provider_prefixed_model",
]
