{{- if and .Values.ingress.enabled .Values.livekit.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: livekit
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.livekitHost }}
      secretName: {{ .Values.ingress.livekitTlsSecretName }}
  rules:
    - host: {{ .Values.ingress.livekitHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: livekit
                port:
                  number: 7880
{{- end }}
