"""Идентификаторы системных типов связей и атрибутов для графа CRM."""

NOTE_VOICE_RELATIONSHIP_TYPE = "note_voice"
IN_CONTEXT_RELATIONSHIP_TYPE = "in_context"
BELONGS_TO_RELATIONSHIP_TYPE = "belongs_to"

PLATFORM_USER_ID_ATTR = "platform_user_id"
PLATFORM_COMPANY_ID_ATTR = "platform_company_id"
PLATFORM_NAMESPACE_ATTR = "platform_namespace"

CONTACT_ENTITY_TYPE = "contact"
MEMBER_ENTITY_TYPE = "member"

NOTE_ROOT_ENTITY_TYPE_ID = "note"
TASK_ROOT_ENTITY_TYPE_ID = "task"
MEETING_ENTITY_TYPE_ID = "meeting"
CALL_ENTITY_TYPE_ID = "call"

NOTE_FAMILY_ENTITY_TYPE_IDS: frozenset[str] = frozenset(
    {NOTE_ROOT_ENTITY_TYPE_ID, MEETING_ENTITY_TYPE_ID, CALL_ENTITY_TYPE_ID}
)
COMPANY_ENTITY_TYPE = "company"
NAMESPACE_ENTITY_TYPE = "namespace"

ENTITY_TYPES_CLONED_INTO_NEW_NAMESPACE: frozenset[str] = frozenset(
    {MEMBER_ENTITY_TYPE, COMPANY_ENTITY_TYPE, NAMESPACE_ENTITY_TYPE}
)

ENTITY_TYPES_EXCLUDED_FROM_NAMESPACE_EDITABILITY_COUNTS: frozenset[str] = frozenset(
    {NAMESPACE_ENTITY_TYPE}
)
